## To create a Webserver with SSL in docker environment, we have to create a Docker Compose service for it
## Use docker-compose up -d, to bring your environment up

version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
      
## docker compose restart, to give access to nginX access to certbot folder
## folder is empty right now. Re-run Certbot without the --dry-run flag to fill the folder with certificates:
## docker compose run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ -d example.org      

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    networks:
          docker-network:
            driver: bridge
      
      
## To renew : docker compose run --rm certbot renew
      